// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWd1nYUxT09nE8vnJUWLRzO4kbVjE9L44',
    appId: '1:776497900380:web:67a1e0ab38095d88c96f99',
    messagingSenderId: '776497900380',
    projectId: 'good2go-1407a',
    authDomain: 'good2go-1407a.firebaseapp.com',
    storageBucket: 'good2go-1407a.appspot.com',
    measurementId: 'G-2PVHV5SXQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNX3wMBOiB6cHUP_fklJ3iNVP-hAkXAOQ',
    appId: '1:776497900380:android:2ccc71975f75b4cfc96f99',
    messagingSenderId: '776497900380',
    projectId: 'good2go-1407a',
    storageBucket: 'good2go-1407a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqb6hEb5xLmUBe7dGe0UkymKUVXC_fgs8',
    appId: '1:776497900380:ios:d7363c3695a7ef4bc96f99',
    messagingSenderId: '776497900380',
    projectId: 'good2go-1407a',
    storageBucket: 'good2go-1407a.appspot.com',
    iosBundleId: 'com.example.good2goApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqb6hEb5xLmUBe7dGe0UkymKUVXC_fgs8',
    appId: '1:776497900380:ios:d7363c3695a7ef4bc96f99',
    messagingSenderId: '776497900380',
    projectId: 'good2go-1407a',
    storageBucket: 'good2go-1407a.appspot.com',
    iosBundleId: 'com.example.good2goApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWd1nYUxT09nE8vnJUWLRzO4kbVjE9L44',
    appId: '1:776497900380:web:39c87eabf6785499c96f99',
    messagingSenderId: '776497900380',
    projectId: 'good2go-1407a',
    authDomain: 'good2go-1407a.firebaseapp.com',
    storageBucket: 'good2go-1407a.appspot.com',
    measurementId: 'G-H1MPL6D8PC',
  );
}
